namespace: emp-app

flask:
  replicaCount: 1
  image:
    repository: ankitaubale/employee-app
    tag: latest
  service:
    port: 5000
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 20

mysql:
  replicaCount: 1
  image: mysql:8.0
  storage:
    size: 1Gi
  secrets:
    rootPassword: root
    database: employee_db
    user: employee_user
    password: root

ingress:
  enabled: true
  hostname: flask.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

httpRoute:
  enabled: false